object frameauftragsdaten: Tframeauftragsdaten
  Left = 0
  Top = 0
  Width = 1028
  Height = 304
  Align = alLeft
  Color = 14933977
  Font.Charset = DEFAULT_CHARSET
  Font.Color = 6908265
  Font.Height = -11
  Font.Name = 'Tahoma'
  Font.Style = []
  ParentBackground = False
  ParentColor = False
  ParentFont = False
  TabOrder = 0
  OnResize = FrameResize
  ExplicitHeight = 650
  object pager: TNxPageControl
    AlignWithMargins = True
    Left = 3
    Top = 3
    Width = 1022
    Height = 298
    ActivePage = NxTabSheet3
    ActivePageIndex = 2
    Align = alClient
    Color = clWhite
    ParentColor = False
    TabOrder = 0
    BackgroundColor = clWhite
    Margin = 0
    Options = [pgBoldActiveTab, pgCloseButton]
    Spacing = 0
    TabHeight = 17
    ExplicitWidth = 781
    object NxTabSheet1: TNxTabSheet
      Caption = 'NxTabSheet1'
      PageIndex = 0
      ParentTabFont = False
      TabFont.Charset = DEFAULT_CHARSET
      TabFont.Color = 6908265
      TabFont.Height = -11
      TabFont.Name = 'Tahoma'
      TabFont.Style = []
      ExplicitTop = 0
      ExplicitWidth = 781
      object FlowPanel1: TFlowPanel
        Left = 0
        Top = 0
        Width = 1022
        Height = 277
        Align = alClient
        BevelOuter = bvNone
        Caption = 'FlowPanel1'
        Color = clWhite
        ParentBackground = False
        TabOrder = 0
        ExplicitWidth = 781
        object pliegenschaft: TPanel
          Left = 0
          Top = 0
          Width = 784
          Height = 105
          Margins.Left = 1
          Margins.Top = 1
          Margins.Right = 1
          Margins.Bottom = 1
          Align = alTop
          BevelOuter = bvNone
          Color = clWhite
          ParentBackground = False
          TabOrder = 0
          object Label7: TLabel
            Left = 32
            Top = 48
            Width = 61
            Height = 13
            Caption = 'Liegenschaft'
            Layout = tlCenter
          end
          object lauftragsnummer: TLabel
            Left = 32
            Top = 70
            Width = 80
            Height = 13
            Caption = 'Auftragsnummer'
            Layout = tlCenter
          end
          object Label2: TLabel
            Left = 614
            Top = 5
            Width = 31
            Height = 13
            Caption = 'Datum'
            Layout = tlCenter
          end
          object Label5: TLabel
            Left = 437
            Top = 70
            Width = 58
            Height = 13
            Caption = 'Auftragstyp'
            Layout = tlCenter
          end
          object Label6: TLabel
            Left = 33
            Top = 24
            Width = 82
            Height = 16
            Caption = 'Stammdaten'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object Label17: TLabel
            Left = 408
            Top = 48
            Width = 87
            Height = 13
            Caption = 'Abrechnungsende'
            Layout = tlCenter
          end
          object eliegenschaft: TfEdit
            Left = 204
            Top = 48
            Width = 146
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            MaxLength = 7
            NumbersOnly = True
            ParentFont = False
            TabOrder = 0
            OnExit = eliegenschaftExit
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object fauftragsnummer: TfEdit
            Left = 204
            Top = 70
            Width = 146
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 1
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object dperstellungsdatum: TNxDatePicker
            Left = 651
            Top = 2
            Width = 122
            Height = 21
            BevelOuter = bvNone
            Color = clWhite
            TabOrder = 2
            Text = '07.10.2014'
            HideFocus = False
            Date = 41919.000000000000000000
            NoneCaption = 'None'
            TodayCaption = 'Today'
          end
          object cbauftragstyp: TfComboBox
            Left = 501
            Top = 70
            Width = 146
            Height = 24
            BevelInner = bvLowered
            BevelKind = bkTile
            BevelOuter = bvNone
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clWindowText
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 3
            Text = 'Auftragstyp'
            Items.Strings = (
              'Nachablesung'
              'Montage'
              'Ger'#228'tetausch')
            TabOnEnter = False
            FontColorOnEnter = 36607
            ColorFocused = 36607
            ColorNotFocused = clBlack
          end
          object dpabrechnungsende: TNxDatePicker
            Left = 501
            Top = 48
            Width = 146
            Height = 21
            BevelInner = bvNone
            BevelOuter = bvNone
            Color = clWhite
            TabOrder = 4
            Text = '07.10.2014'
            HideFocus = False
            Date = 41919.000000000000000000
            NoneCaption = 'None'
            TodayCaption = 'Today'
          end
        end
        object pauftragsdaten: TPanel
          Left = 0
          Top = 105
          Width = 784
          Height = 115
          Margins.Left = 1
          Margins.Top = 0
          Margins.Right = 1
          Margins.Bottom = 1
          Align = alTop
          BevelOuter = bvNone
          Color = clWhite
          ParentBackground = False
          TabOrder = 1
          object Label8: TLabel
            Left = 32
            Top = 16
            Width = 89
            Height = 16
            Caption = 'Auftraggeber'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object Label9: TLabel
            Left = 32
            Top = 42
            Width = 54
            Height = 13
            Caption = 'Eigent'#252'mer'
            Layout = tlCenter
          end
          object Label10: TLabel
            Left = 32
            Top = 65
            Width = 32
            Height = 13
            Caption = 'Stra'#223'e'
            Layout = tlCenter
          end
          object Label11: TLabel
            Left = 32
            Top = 86
            Width = 17
            Height = 13
            Caption = 'PLZ'
            Layout = tlCenter
          end
          object Label12: TLabel
            Left = 56
            Top = 86
            Width = 16
            Height = 13
            Caption = 'Ort'
            Layout = tlCenter
          end
          object ename1: TfEdit
            Left = 200
            Top = 42
            Width = 224
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            CharCase = ecUpperCase
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = True
            ParentFont = False
            TabOrder = 0
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object estrasse: TfEdit
            Left = 200
            Top = 64
            Width = 448
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            CharCase = ecUpperCase
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = True
            ParentFont = False
            TabOrder = 2
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object eort: TfEdit
            Left = 240
            Top = 86
            Width = 408
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            CharCase = ecUpperCase
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = True
            ParentFont = False
            TabOrder = 4
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object eplz: TfEdit
            Left = 200
            Top = 86
            Width = 41
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            CharCase = ecUpperCase
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            NumbersOnly = True
            ParentColor = True
            ParentFont = False
            TabOrder = 3
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object ename2: TfEdit
            Left = 423
            Top = 42
            Width = 225
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            CharCase = ecUpperCase
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentColor = True
            ParentFont = False
            TabOrder = 1
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
        end
        object perreichbarkeit: TPanel
          Left = 0
          Top = 220
          Width = 781
          Height = 197
          Margins.Left = 1
          Margins.Top = 0
          Margins.Right = 1
          Margins.Bottom = 1
          Align = alTop
          Alignment = taLeftJustify
          BevelOuter = bvNone
          Color = clWhite
          ParentBackground = False
          TabOrder = 2
          object lnutzername: TLabel
            Left = 33
            Top = 61
            Width = 58
            Height = 13
            Caption = 'Nutzername'
            Layout = tlCenter
          end
          object lerreichbarkeit: TLabel
            Left = 32
            Top = 16
            Width = 91
            Height = 16
            Caption = 'Erreichbarkeit'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object lemail: TLabel
            Left = 32
            Top = 82
            Width = 24
            Height = 13
            Caption = 'Email'
            Layout = tlCenter
          end
          object ltelefon: TLabel
            Left = 32
            Top = 105
            Width = 36
            Height = 13
            Caption = 'Telefon'
            Layout = tlCenter
          end
          object lnutzernr: TLabel
            Left = 32
            Top = 39
            Width = 70
            Height = 13
            Caption = 'Nutzernummer'
            Layout = tlCenter
          end
          object lausfürhung: TLabel
            Left = 644
            Top = 16
            Width = 125
            Height = 16
            Caption = 'Ausf'#252'hrungstermin'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object Label15: TLabel
            Left = 32
            Top = 126
            Width = 87
            Height = 13
            Caption = 'Nutzer wurde per '
          end
          object Label16: TLabel
            Left = 326
            Top = 133
            Width = 46
            Height = 13
            Caption = 'informiert'
          end
          object enutzername1: TfEdit
            Left = 200
            Top = 61
            Width = 224
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            CharCase = ecUpperCase
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 1
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object eemail: TfEdit
            Left = 200
            Top = 82
            Width = 448
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 2
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object etelefon: TfEdit
            Left = 200
            Top = 104
            Width = 448
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 3
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object enutzernummer: TfEdit
            Left = 200
            Top = 39
            Width = 34
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            CharCase = ecUpperCase
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            MaxLength = 3
            NumbersOnly = True
            ParentFont = False
            TabOrder = 0
            OnExit = enutzernummerExit
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object pausführung: TPanel
            Left = 654
            Top = 39
            Width = 115
            Height = 130
            BevelOuter = bvNone
            Caption = '  '
            Color = clWhite
            ParentBackground = False
            TabOrder = 4
            object ldayOM: TLabel
              Left = 32
              Top = -6
              Width = 31
              Height = 58
              Caption = '7'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = 6908265
              Font.Height = -48
              Font.Name = 'Tahoma'
              Font.Style = [fsBold]
              ParentFont = False
            end
            object Lmy: TLabel
              Left = 0
              Top = 58
              Width = 88
              Height = 25
              Alignment = taCenter
              Caption = 'Aug 2014'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = 6908265
              Font.Height = -21
              Font.Name = 'Tahoma'
              Font.Style = []
              ParentFont = False
            end
            object lvon: TLabel
              Left = 0
              Top = 92
              Width = 42
              Height = 19
              Align = alCustom
              Caption = '12:00'
              Font.Charset = DEFAULT_CHARSET
              Font.Color = 6908265
              Font.Height = -16
              Font.Name = 'Tahoma'
              Font.Style = []
              ParentFont = False
              Layout = tlCenter
            end
            object pdivisor: TPanel
              Left = 0
              Top = 90
              Width = 100
              Height = 2
              TabOrder = 0
            end
          end
          object Button1: TButton
            Left = 649
            Top = 156
            Width = 114
            Height = 25
            Caption = 'Termin festsetzen'
            TabOrder = 5
            OnClick = Button1Click
          end
          object NxComboBox1: TNxComboBox
            Left = 200
            Top = 126
            Width = 120
            Height = 21
            BevelInner = bvNone
            TabOrder = 6
            HideFocus = False
            AutoCompleteDelay = 0
            Items.Strings = (
              'Email'
              'Anruf'
              'Brief'
              'Postkarte'
              'Hausaushang')
          end
          object enutzername2: TfEdit
            Left = 423
            Top = 61
            Width = 225
            Height = 23
            AutoSize = False
            BevelInner = bvLowered
            BevelKind = bkTile
            CharCase = ecUpperCase
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 7
            TabOnEnter = False
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
        end
        object pnotizen: TPanel
          Left = 0
          Top = 417
          Width = 784
          Height = 352
          Margins.Left = 1
          Margins.Top = 0
          Margins.Right = 1
          Margins.Bottom = 1
          Align = alTop
          BevelOuter = bvNone
          Color = clWhite
          ParentBackground = False
          TabOrder = 3
          object lcharleft: TLabel
            Left = 641
            Top = 103
            Width = 122
            Height = 13
            Caption = 'noch 612 Zeichen m'#246'glich'
            Layout = tlCenter
          end
          object Label4: TLabel
            Left = 32
            Top = 16
            Width = 48
            Height = 16
            Caption = 'Notizen'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
          end
          object notizen: TfMemo
            Left = 200
            Top = 19
            Width = 563
            Height = 78
            BevelInner = bvLowered
            BevelKind = bkTile
            Color = clWhite
            Font.Charset = DEFAULT_CHARSET
            Font.Color = 6908265
            Font.Height = -13
            Font.Name = 'Tahoma'
            Font.Style = [fsBold]
            ParentFont = False
            TabOrder = 0
            OnKeyDown = notizenKeyDown
            FontColorOnEnter = 10252872
            ColorFocused = 10252872
            ColorNotFocused = 11776947
          end
          object NxButton1: TNxButton
            Left = 512
            Top = 245
            Width = 137
            Caption = 'Werte zur'#252'cksetzen'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 1
            OnClick = NxButton1Click
          end
          object NxButton4: TNxButton
            Left = 369
            Top = 245
            Width = 137
            Caption = 'abschlie'#223'en'
            Font.Charset = DEFAULT_CHARSET
            Font.Color = clBlack
            Font.Height = -11
            Font.Name = 'Tahoma'
            Font.Style = []
            ParentFont = False
            TabOrder = 2
          end
        end
      end
      object hptermin: TNxHeaderPanel
        Left = 45
        Top = 278
        Width = 888
        Height = 374
        AdaptiveColors = False
        BorderWidth = 0
        Caption = 'Termin festlegen'
        CollapseWidth = 126
        DockSite = True
        DragKind = dkDock
        HeaderColor = 13743257
        HeaderFont.Charset = DEFAULT_CHARSET
        HeaderFont.Color = 6908265
        HeaderFont.Height = -11
        HeaderFont.Name = 'Tahoma'
        HeaderFont.Style = []
        HeaderStyle = psFlat
        Options = [hoClickOnBodyExpand, hoCollapseButton]
        ParentHeaderFont = False
        TabOrder = 1
        OnCollapse = hpterminCollapse
        OnExpand = hpterminExpand
        FullWidth = 888
        object cbableser: TfComboBox
          Left = 384
          Top = 242
          Width = 145
          Height = 24
          BevelInner = bvLowered
          BevelKind = bkTile
          BevelOuter = bvNone
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 0
          Text = 'cbableser'
          TabOnEnter = False
          FontColorOnEnter = 36607
          ColorFocused = 36607
          ColorNotFocused = clBlack
        end
      end
    end
    object NxTabSheet2: TNxTabSheet
      Caption = 'NxTabSheet2'
      PageIndex = 1
      ParentTabFont = False
      TabFont.Charset = DEFAULT_CHARSET
      TabFont.Color = 6908265
      TabFont.Height = -11
      TabFont.Name = 'Tahoma'
      TabFont.Style = []
      ExplicitTop = 0
      ExplicitWidth = 781
      object perreichtdetails: TPanel
        Left = 0
        Top = 0
        Width = 1022
        Height = 277
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Align = alClient
        BevelOuter = bvNone
        Color = clWhite
        ParentBackground = False
        TabOrder = 0
        ExplicitWidth = 781
        object Label18: TLabel
          Left = 29
          Top = 35
          Width = 87
          Height = 13
          Caption = 'Nutzer wurde per '
        end
        object Label19: TLabel
          Left = 259
          Top = 35
          Width = 46
          Height = 13
          Caption = 'informiert'
        end
        object Label20: TLabel
          Left = 32
          Top = 79
          Width = 69
          Height = 13
          Caption = 'informiert am  '
        end
        object NxComboBox2: TNxComboBox
          Left = 125
          Top = 35
          Width = 120
          Height = 21
          BevelInner = bvNone
          TabOrder = 0
          HideFocus = False
          AutoCompleteDelay = 0
          Items.Strings = (
            'Email'
            'Anruf'
            'Brief'
            'Postkarte'
            'Hausaushang')
        end
        object NxCheckBox62: TNxCheckBox6
          Left = 30
          Top = 118
          Width = 97
          Height = 17
          TagString = ''
          Caption = 'Nutzer erreicht'
          TabOrder = 1
        end
        object NxButton8: TNxButton
          Left = 124
          Top = 159
          Width = 75
          Caption = 'speichern'
          TabOrder = 2
          OnClick = NxButton8Click
        end
        object NxButton9: TNxButton
          Left = 215
          Top = 159
          Width = 75
          Caption = 'verwerfen'
          TabOrder = 3
          OnClick = NxButton7Click
        end
        object einfodate: TfEdit
          Left = 125
          Top = 74
          Width = 116
          Height = 23
          AutoSize = False
          BevelInner = bvLowered
          BevelKind = bkTile
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 4
          TextHint = 'ttmmjj'
          TabOnEnter = False
          FontColorOnEnter = 36607
          ColorFocused = 36607
          ColorNotFocused = clBlack
        end
        object NxMonthCalendar2: TNxMonthCalendar
          Left = 344
          Top = 35
          Width = 151
          Height = 163
          Day = 29
          Month = 10
          NoneCaption = 'None'
          SelectedDate = 41941.000000000000000000
          TodayCaption = 'Today'
          Year = 2014
          OnChange = NxMonthCalendar2Change
        end
      end
    end
    object NxTabSheet3: TNxTabSheet
      Caption = 'NxTabSheet3'
      PageIndex = 2
      ParentTabFont = False
      TabFont.Charset = DEFAULT_CHARSET
      TabFont.Color = 6908265
      TabFont.Height = -11
      TabFont.Name = 'Tahoma'
      TabFont.Style = []
      ExplicitTop = 0
      ExplicitWidth = 781
      object ptermindetails: TNxPanel
        Left = 0
        Top = 0
        Width = 1022
        Height = 277
        Margins.Left = 5
        Margins.Top = 5
        Margins.Right = 5
        Margins.Bottom = 5
        AdaptiveColors = False
        Align = alClient
        BorderPen.Color = 14933977
        BorderPen.Style = psClear
        Color = clWhite
        ColorScheme = csSilver2010
        UseDockManager = False
        FullRepaint = True
        ParentColor = False
        TabOrder = 0
        ExplicitWidth = 781
        object Label13: TLabel
          Left = 192
          Top = 61
          Width = 31
          Height = 13
          Caption = 'Datum'
        end
        object Label14: TLabel
          Left = 192
          Top = 97
          Width = 21
          Height = 13
          Caption = 'von '
        end
        object Label3: TLabel
          Left = 192
          Top = 133
          Width = 13
          Height = 13
          Caption = 'bis'
        end
        object mitHA: TCheckBox
          Left = 567
          Top = 60
          Width = 161
          Height = 17
          Caption = 'mit der Hauptablesung'
          TabOrder = 2
          OnClick = mitHAClick
        end
        object NxButton2: TNxButton
          Left = 451
          Top = 194
          Width = 75
          Caption = 'speichern'
          TabOrder = 0
          OnClick = NxButton2Click
        end
        object NxButton3: TNxButton
          Left = 558
          Top = 194
          Width = 75
          Caption = 'verwerfen'
          TabOrder = 1
          OnClick = NxButton3Click
        end
        object nxdate: TNxMonthCalendar
          Left = 86
          Top = 417
          Width = 151
          Height = 163
          Day = 8
          Month = 10
          NoneCaption = 'None'
          SelectedDate = 41920.000000000000000000
          TodayCaption = 'Today'
          Year = 2014
          OnChange = nxdateChange
        end
        object externGeplant: TCheckBox
          Left = 567
          Top = 83
          Width = 161
          Height = 17
          Caption = 'extern geplant'
          TabOrder = 4
          OnClick = mitHAClick
        end
        object edate: TfEdit
          Left = 264
          Top = 57
          Width = 121
          Height = 23
          AutoSize = False
          BevelInner = bvLowered
          BevelKind = bkTile
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 5
          TextHint = 'ttmmjj'
          TabOnEnter = False
          FontColorOnEnter = 36607
          ColorFocused = 36607
          ColorNotFocused = clBlack
        end
        object evon: TfEdit
          Left = 264
          Top = 96
          Width = 121
          Height = 23
          AutoSize = False
          BevelInner = bvLowered
          BevelKind = bkTile
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 6
          TextHint = 'ssmm'
          OnExit = evonExit
          TabOnEnter = False
          FontColorOnEnter = 36607
          ColorFocused = 36607
          ColorNotFocused = clBlack
        end
        object ebis: TfEdit
          Left = 264
          Top = 140
          Width = 121
          Height = 23
          AutoSize = False
          BevelInner = bvLowered
          BevelKind = bkTile
          Font.Charset = DEFAULT_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Tahoma'
          Font.Style = []
          ParentFont = False
          TabOrder = 7
          TextHint = 'ssmm'
          OnExit = evonExit
          TabOnEnter = False
          FontColorOnEnter = 36607
          ColorFocused = 36607
          ColorNotFocused = clBlack
        end
        object NxTimePicker1: TNxTimePicker
          Left = 326
          Top = 58
          Width = 121
          Height = 21
          TabOrder = 8
          Text = '15:20:00'
          HideFocus = False
          Time = 0.638888888888888800
          HoursString = 'H'
          MinutesString = 'M'
          UseStandardMinute = True
        end
        object NxHeaderPanel1: TNxHeaderPanel
          Left = 272
          Top = 264
          Caption = ''
          HeaderFont.Charset = DEFAULT_CHARSET
          HeaderFont.Color = 6908265
          HeaderFont.Height = -11
          HeaderFont.Name = 'Tahoma'
          HeaderFont.Style = []
          ParentHeaderFont = False
          TabOrder = 9
          FullWidth = 245
        end
      end
    end
  end
end
